"""Phase-0 tests for RegexSet: union NFA + tagged Pike reference.

Anchor-free expectations are generated by the O(n^2) sweep oracle
(tools/set_oracle.py) — all-ends semantics cannot be derived from
re.finditer. Anchored and word-boundary cases are hand-derived (the
sweep is unsound for them: slicing breaks relative anchoring).
"""

from emberregex import SetMatch, RegexSet
from emberregex.set_nfa import build_union_nfa, matches_empty_buffer
from emberregex.set_pike import set_pike_scan
from std.testing import assert_equal, assert_raises, assert_true, TestSuite


def assert_reports(
    got: List[SetMatch], expected: List[SetMatch], label: String
) raises:
    var ok = len(got) == len(expected)
    if ok:
        for i in range(len(got)):
            if got[i] != expected[i]:
                ok = False
                break
    if not ok:
        var msg = String(label, ": got [")
        for i in range(len(got)):
            msg.write(got[i], " ")
        msg.write("] expected [")
        for i in range(len(expected)):
            msg.write(expected[i], " ")
        msg.write("]")
        assert_true(False, msg)


# --- Oracle-generated (tools/set_oracle.py) ---------------------------------


def test_alternation_reports_all_ends() raises:
    # The canonical trap: `ab|a` on "ab" must report end 1 AND end 2.
    var db = RegexSet[["ab|a", "b"]]()
    assert_reports(
        db.scan("ab"),
        [SetMatch(0, 1), SetMatch(0, 2), SetMatch(1, 2)],
        "alt_all_ends",
    )


def test_shared_prefix_literals() raises:
    var db = RegexSet[["ab", "abc", "abcd"]]()
    assert_reports(
        db.scan("xabcdab"),
        [SetMatch(0, 3), SetMatch(1, 4), SetMatch(2, 5), SetMatch(0, 7)],
        "shared_prefix",
    )


def test_plus_reports_every_end() raises:
    var db = RegexSet[["a+"]]()
    assert_reports(
        db.scan("aaa"),
        [SetMatch(0, 1), SetMatch(0, 2), SetMatch(0, 3)],
        "plus_all_ends",
    )


def test_duplicate_patterns_distinct_ids() raises:
    var db = RegexSet[["foo", "foo"]]()
    assert_reports(
        db.scan("a foo"),
        [SetMatch(0, 5), SetMatch(1, 5)],
        "duplicates",
    )


def test_high_bytes() raises:
    # Byte-mode literals >= 0x80: "é" is the two-byte chain C3 A9; \xff
    # arrives via the regex-level hex escape. Input goes through the Span
    # overload so it can carry a raw 0xFF byte.
    var db = RegexSet[["é", "\\xff"]]()
    var data: List[Byte] = [120, 0xC3, 0xA9, 121, 0xFF]
    assert_reports(
        db.scan(Span(data)),
        [SetMatch(0, 3), SetMatch(1, 5)],
        "high_bytes",
    )


def test_per_pattern_caseless() raises:
    var db = RegexSet[["(?i)foo", "bar"]]()
    assert_reports(
        db.scan("FOO bar Foo"),
        [SetMatch(0, 3), SetMatch(1, 7), SetMatch(0, 11)],
        "caseless_mix",
    )


def test_per_pattern_dotall() raises:
    var db = RegexSet[["a.b", "(?s)a.b"]]()
    assert_reports(
        db.scan("a\nb axb"),
        [SetMatch(1, 3), SetMatch(0, 7), SetMatch(1, 7)],
        "dotall",
    )


def test_char_classes() raises:
    var db = RegexSet[["\\d+", "[a-z]+"]]()
    assert_reports(
        db.scan("ab 12"),
        [SetMatch(1, 1), SetMatch(1, 2), SetMatch(0, 4), SetMatch(0, 5)],
        "classes",
    )


def test_log_triage_set() raises:
    var db = RegexSet[["ERROR", "WARN", "timeout", "\\d+ms"]]()
    assert_reports(
        db.scan("[WARN] request timeout after 1500ms; ERROR: retry 2ms"),
        [
            SetMatch(1, 5),
            SetMatch(2, 22),
            SetMatch(3, 35),
            SetMatch(0, 42),
            SetMatch(3, 53),
        ],
        "log_triage",
    )


def test_overlap_dense_tie_order() raises:
    # Ties at one end must come out in ascending id order.
    var db = RegexSet[["aa", "aaa", "a"]]()
    assert_reports(
        db.scan("aaaa"),
        [
            SetMatch(2, 1),
            SetMatch(0, 2),
            SetMatch(2, 2),
            SetMatch(0, 3),
            SetMatch(1, 3),
            SetMatch(2, 3),
            SetMatch(0, 4),
            SetMatch(1, 4),
            SetMatch(2, 4),
        ],
        "overlap_dense",
    )


# --- Hand-derived (anchored / word-boundary: sweep oracle unsound) ----------


def test_anchor_bol() raises:
    var db = RegexSet[["^ab"]]()
    assert_reports(db.scan("ab ab"), [SetMatch(0, 2)], "anchor_bol")


def test_anchor_eol() raises:
    var db = RegexSet[["ab$"]]()
    assert_reports(db.scan("ab ab"), [SetMatch(0, 5)], "anchor_eol")


def test_anchor_bol_multiline() raises:
    var db = RegexSet[["(?m)^ab"]]()
    assert_reports(
        db.scan("ab\nab"),
        [SetMatch(0, 2), SetMatch(0, 5)],
        "anchor_bol_multiline",
    )


def test_anchor_eol_multiline() raises:
    var db = RegexSet[["(?m)ab$"]]()
    assert_reports(
        db.scan("ab\nab"),
        [SetMatch(0, 2), SetMatch(0, 5)],
        "anchor_eol_multiline",
    )


def test_word_boundary() raises:
    var db = RegexSet[["\\bcat\\b", "cat"]]()
    assert_reports(
        db.scan("cat catalog"),
        [SetMatch(0, 3), SetMatch(1, 3), SetMatch(1, 7)],
        "word_boundary",
    )


def test_empty_input() raises:
    var db = RegexSet[["a", "b"]]()
    assert_reports(db.scan(""), List[SetMatch](), "empty_input")


def test_allow_empty_reports_every_position() raises:
    var db = RegexSet[["a*"], True]()
    assert_reports(
        db.scan("ba"),
        [SetMatch(0, 0), SetMatch(0, 1), SetMatch(0, 2)],
        "allow_empty",
    )


def test_single_pattern_set() raises:
    var db = RegexSet[["abc"]]()
    assert_reports(db.scan("zabcz"), [SetMatch(0, 4)], "single_pattern")


def test_capture_demotion() raises:
    # Groups compile but never surface: only (id, end) reports.
    var db = RegexSet[["(ab)+"]]()
    assert_reports(
        db.scan("abab"),
        [SetMatch(0, 2), SetMatch(0, 4)],
        "capture_demotion",
    )


def test_more_than_eight_patterns() raises:
    var db = RegexSet[["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8"]]()
    assert_reports(
        db.scan("a3 a8"),
        [SetMatch(3, 2), SetMatch(8, 5)],
        "nine_patterns",
    )


# --- Build-time validation ---------------------------------------------------


def test_vacuous_patterns_rejected() raises:
    with assert_raises():
        _ = build_union_nfa(["a*"], False)
    with assert_raises():
        _ = build_union_nfa([""], False)
    with assert_raises():
        _ = build_union_nfa(["a|b*"], False)
    with assert_raises():
        _ = build_union_nfa(["^"], False)
    with assert_raises():
        _ = build_union_nfa(["x?"], False)
    # Non-vacuous builds fine; allow_empty permits vacuous.
    _ = build_union_nfa(["a+"], False)
    _ = build_union_nfa(["a*"], True)


def test_backref_and_lookaround_are_widened_not_rejected() raises:
    # Phase 7 replaced rejection with widen-and-confirm: these build, and
    # the union NFA records which ids need the exact engine afterwards
    # (set_prefilter.mojo). Behaviour is pinned in test_set_phase7.mojo.
    var a = build_union_nfa(["(a)\\1"], False)
    assert_equal(len(a.confirm_ids), 1)
    var b = build_union_nfa(["(?=a)b"], False)
    assert_equal(len(b.confirm_ids), 1)
    var c = build_union_nfa(["(?<=a)b"], False)
    assert_equal(len(c.confirm_ids), 1)
    # A pattern needing no widening records nothing.
    var d = build_union_nfa(["abc"], False)
    assert_equal(len(d.confirm_ids), 0)
    # A backreference that cannot be resolved still refuses to build.
    with assert_raises():
        _ = build_union_nfa(["\\1(a)"], False)


def test_empty_pattern_list_rejected() raises:
    with assert_raises():
        _ = build_union_nfa(List[String](), False)


def test_matches_empty_buffer_detector() raises:
    var vac = build_union_nfa(["a*"], True)
    assert_true(matches_empty_buffer(vac, vac.start))
    var solid = build_union_nfa(["a+"], False)
    assert_true(not matches_empty_buffer(solid, solid.start))


def test_word_boundary_vacuity() raises:
    # \b fails on the empty buffer (no word char on either side), so a
    # bare \b is NOT vacuous and must build without allow_empty...
    var db = RegexSet[["\\b"]]()
    # ...and reports zero-width at both boundaries of "a".
    assert_reports(db.scan("a"), [SetMatch(0, 0), SetMatch(0, 1)], "bare_wb")
    # \B holds at position 0 of the empty buffer: vacuous, rejected
    # unless allow_empty.
    with assert_raises():
        _ = build_union_nfa(["\\B"], False)
    _ = build_union_nfa(["\\B"], True)


def test_pike_reference_anchors_directly() raises:
    # The reference engine is the oracle for every faster lane, so its
    # own line-anchor behavior gets direct (non-lane-routed) pins —
    # including a trailing-newline input, where this library's strict $
    # (end-of-input only, unlike PCRE) must NOT fire.
    var bol = build_union_nfa(["^ab"])
    assert_reports(
        set_pike_scan(bol, "ab ab".as_bytes()),
        [SetMatch(0, 2)],
        "pike ^ab",
    )
    var eol = build_union_nfa(["ab$"])
    assert_reports(
        set_pike_scan(eol, "ab ab".as_bytes()),
        [SetMatch(0, 5)],
        "pike ab$",
    )
    assert_reports(
        set_pike_scan(eol, "ab\n".as_bytes()),
        List[SetMatch](),
        "pike ab$ trailing newline",
    )
    var mbol = build_union_nfa(["(?m)^ab"])
    assert_reports(
        set_pike_scan(mbol, "ab\nab".as_bytes()),
        [SetMatch(0, 2), SetMatch(0, 5)],
        "pike (?m)^ab",
    )
    var meol = build_union_nfa(["(?m)ab$"])
    assert_reports(
        set_pike_scan(meol, "ab\nab\n".as_bytes()),
        [SetMatch(0, 2), SetMatch(0, 5)],
        "pike (?m)ab$",
    )


def test_comptime_properties() raises:
    comptime S = RegexSet[["cat", "dog"]]
    assert_equal(S.num_patterns, 2)
    comptime n_states = len(S.nfa.states)
    assert_true(n_states > 0)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
