[workspace]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "emberregex"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = { cmd = "python3 run_test.py" }
build = { cmd = "mojo build emberregex/__init__.mojo -o emberregex"}
bench = { cmd = "mojo -I . bench/bench.mojo" }
bench_static = { cmd = "mojo -I . bench/static/bench_static.mojo" }
bench_all = {depends-on=["bench", "bench_static"]}
compare = { cmd = "python3 bench/bench_compare.py" }
format = "mojo format emberregex test bench"

[dependencies]
mojo = ">=0.26.3.0.dev2026032005,<0.27"

[feature.pdf.dependencies]
reportlab = "*"

[feature.pdf.tasks]
compare_pdf = { cmd = "python3 bench/gen_pdf.py" }

[environments]
default = { features = [], solve-group = "default" }
pdf = { features = ["pdf"], solve-group = "default" }
