"""Compile-time character constants."""


def __to_byte[c: StringLiteral]() -> Byte:
    return Byte(ord(c))


comptime CHAR_A_LOWER = __to_byte["a"]()
comptime CHAR_A_UPPER = __to_byte["A"]()
comptime CHAR_BACKSLASH = __to_byte["\\"]()
comptime CHAR_BANG = __to_byte["!"]()
comptime CHAR_B_LOWER = __to_byte["b"]()
comptime CHAR_B_UPPER = __to_byte["B"]()
comptime CHAR_C_LOWER = __to_byte["c"]()
comptime CHAR_CARET = __to_byte["^"]()
comptime CHAR_COLON = __to_byte[":"]()
comptime CHAR_COMMA = __to_byte[","]()
comptime CHAR_CR = __to_byte["\r"]()
comptime CHAR_DOLLAR = __to_byte["$"]()
comptime CHAR_DOT = __to_byte["."]()
comptime CHAR_D_LOWER = __to_byte["d"]()
comptime CHAR_D_UPPER = __to_byte["D"]()
comptime CHAR_EQUALS = __to_byte["="]()
comptime CHAR_F_LOWER = __to_byte["f"]()
comptime CHAR_F_UPPER = __to_byte["F"]()
comptime CHAR_GREATER_THAN = __to_byte[">"]()
comptime CHAR_G_LOWER = __to_byte["g"]()
comptime CHAR_HASH = __to_byte["#"]()
comptime CHAR_I_LOWER = __to_byte["i"]()
comptime CHAR_LBRACE = __to_byte["{"]()
comptime CHAR_LBRACKET = __to_byte["["]()
comptime CHAR_LESS_THAN = __to_byte["<"]()
comptime CHAR_LPAREN = __to_byte["("]()
comptime CHAR_MINUS = __to_byte["-"]()
comptime CHAR_M_LOWER = __to_byte["m"]()
comptime CHAR_NEWLINE = __to_byte["\n"]()
comptime CHAR_NINE = __to_byte["9"]()
comptime CHAR_ONE = __to_byte["1"]()
comptime CHAR_PIPE = __to_byte["|"]()
comptime CHAR_PLUS = __to_byte["+"]()
comptime CHAR_P_LOWER = __to_byte["p"]()
comptime CHAR_P_UPPER = __to_byte["P"]()
comptime CHAR_QUESTION = __to_byte["?"]()
comptime CHAR_RBRACE = __to_byte["}"]()
comptime CHAR_RBRACKET = __to_byte["]"]()
comptime CHAR_RPAREN = __to_byte[")"]()
comptime CHAR_S = __to_byte["S"]()
comptime CHAR_SEVEN = __to_byte["7"]()
comptime CHAR_SPACE = __to_byte[" "]()
comptime CHAR_STAR = __to_byte["*"]()
comptime CHAR_S_LOWER = __to_byte["s"]()
comptime CHAR_TAB = __to_byte["\t"]()
comptime CHAR_U_LOWER = __to_byte["u"]()
comptime CHAR_U_UPPER = __to_byte["U"]()
comptime CHAR_UNDERSCORE = __to_byte["_"]()
comptime CHAR_W_LOWER = __to_byte["w"]()
comptime CHAR_W_UPPER = __to_byte["W"]()
comptime CHAR_X_LOWER = __to_byte["x"]()
comptime CHAR_ZERO = __to_byte["0"]()
comptime CHAR_Z_LOWER = __to_byte["z"]()
comptime CHAR_Z_UPPER = __to_byte["Z"]()
comptime CHAR_H_LOWER = __to_byte["h"]()
comptime CHAR_H_UPPER = __to_byte["H"]()
comptime CHAR_V_LOWER = __to_byte["v"]()
comptime CHAR_V_UPPER = __to_byte["V"]()
comptime CHAR_VTAB = __to_byte["\x0b"]()
comptime CHAR_FF = __to_byte["\x0c"]()
comptime CHAR_n = __to_byte["n"]()
comptime CHAR_r = __to_byte["r"]()
comptime CHAR_t = __to_byte["t"]()
