"""Generate emberregex/case_tables.mojo: Python `re`'s IGNORECASE orbits.

Under IGNORECASE a str pattern in CPython's `re` matches a character `c`
against a pattern character `p` when `tolower(c)` is `tolower(p)` or one
of `_EXTRA_CASES[tolower(p)]` (the `re._casefix` table: `i`/`ı`, `s`/`ſ`,
`µ`/`μ`, ...). `tolower` is `_sre.unicode_tolower`, the SIMPLE lowercase
mapping. That relation is an equivalence, so the codepoints split into
orbits; a folded literal matches its whole orbit and a folded class the
union of its members' orbits. Only orbits of two or more are emitted.

The source is CPython itself rather than the `regex` module the property
tables come from (tools/gen_unicode_tables.py), because the behavior being
reproduced IS CPython's `_sre`, on CPython's Unicode version.

Usage:
    python3 tools/gen_case_tables.py > emberregex/case_tables.mojo
"""

import sys
import unicodedata

import _sre
from re._casefix import _EXTRA_CASES


def orbits() -> list[list[int]]:
    key = {}
    for cp in range(0x110000):
        lo = _sre.unicode_tolower(cp)
        group = (lo,) + _EXTRA_CASES.get(lo, ())
        key.setdefault(min(group), []).append(cp)
    return sorted((sorted(m) for m in key.values() if len(m) > 1), key=lambda m: m[0])


# Every table is padded to this many entries so utf8.mojo can load it into
# one `SIMD[int32, CASE_W]` with a single vector op.
CASE_W = 4096
PAD = 0x7FFFFFFF


def emit(name: str, values: list[int], doc: str):
    assert len(values) <= CASE_W, name
    values = values + [PAD] * (CASE_W - len(values))
    print(f"# {doc}")
    print(f"comptime {name}: List[Int] = [")
    for i in range(0, len(values), 8):
        print("    " + ", ".join(f"0x{v:X}" for v in values[i:i + 8]) + ",")
    print("]")
    print()


def main():
    orbs = orbits()
    cps, orbit_of, starts, members = [], [], [], []
    for oid, orb in enumerate(orbs):
        starts.append(len(members))
        members.extend(orb)
        for cp in orb:
            cps.append(cp)
            orbit_of.append(oid)
    starts.append(len(members))
    order = sorted(range(len(cps)), key=lambda i: cps[i])
    cps = [cps[i] for i in order]
    orbit_of = [orbit_of[i] for i in order]

    print('"""Case-insensitive orbits for `(?iu)`: CPython `re` IGNORECASE.')
    print()
    print("GENERATED by tools/gen_case_tables.py — do not edit by hand.")
    print(f"CPython {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.")
    print(f"{len(orbs)} orbits over {len(cps)} codepoints. Each table is padded")
    print(f"to CASE_W entries with 0x{PAD:X}.")
    print('"""')
    print()
    print(f"comptime CASE_W = {CASE_W}")
    print(f"comptime CASE_NCPS = {len(cps)}")
    print(f"comptime CASE_NORBITS = {len(orbs)}")
    print()
    emit("CASE_CPS", cps, "Every codepoint in an orbit of two or more, ascending.")
    emit("CASE_ORBIT_OF", orbit_of, "Orbit id of `CASE_CPS[i]`.")
    emit("CASE_ORBIT_START", starts,
         "Orbit `k` is `CASE_ORBIT_MEMBERS[START[k]:START[k + 1]]`.")
    emit("CASE_ORBIT_MEMBERS", members, "Each orbit's members, ascending.")
    lower = [(cp, _sre.unicode_tolower(cp)) for cp in range(0x110000)
             if _sre.unicode_tolower(cp) != cp]
    print(f"comptime CASE_NLOWER = {len(lower)}")
    print()
    emit("CASE_LOWER_KEYS", [a for a, _ in lower],
         "`(?iu)` backreferences compare `_sre.unicode_tolower` of each "
         "codepoint:\n# every codepoint it changes, ascending ...")
    emit("CASE_LOWER_VALS", [b for _, b in lower], "... and what it maps to.")


if __name__ == "__main__":
    main()
